FROM osrf/ros:kinetic-desktop-full

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV ROS_DISTRO kinetic

ENV SHELL=/bin/bash \
    USER=locobot \
    UID=1000


RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${UID} \
    ${USER} 
    
ENV HOME=/home/${USER}

WORKDIR /home/${USER}

RUN cp /root/.bashrc ~/.bashrc

RUN echo "root:root" | chpasswd
RUN echo "${USER}:locobot" | chpasswd

RUN apt-get -o Acquire::ForceIPv4=true update && apt-get -yq dist-upgrade \
    && apt-get -o Acquire::ForceIPv4=true install -yq --no-install-recommends \
    locales \
    curl \
    cmake \
    make \
    git \
    vim \
    wget \
    sudo \
    lsb-release \
    build-essential \
    net-tools \
    apt-utils \
    software-properties-common \
    dialog \
    libffi-dev \
    python3-dev \
    python3-pip \
    python3-setuptools \
    ros-${ROS_DISTRO}-joy-teleop \
    ros-${ROS_DISTRO}-libcreate \
    && rosdep update

COPY locobot_install_all.sh .

RUN pip3 install --upgrade "pip < 21.0" \
    && pip3 install --upgrade setuptools \
    && pip3 install setuptools

RUN apt install python3-dev -y

RUN apt install apt-transport-https -yq

RUN ./locobot_install_all.sh -t full -p 3 -l interbotix

